name: Bump Version

on:
  push:
    branches:
      - master
    paths:
      - "**"
      - "!README.md"

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Bump Version
        id: bump_version
        uses: Srlion/float-version-semantic@2811c4af2d8e37a37d3b8113ca5a07b4152be2fd
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
